[env]
HCLOUD_TOKEN = {required = true}

[tools]
terraform = "1"
terraform-ls = "latest"
# NOTE: ansible is installed through the requirements.txt file since the
#       mise install of ansible does not play well together with the venv

[tasks."terraform"]
description = "Run Terraform Command"
run = "terraform -chdir=terraform"
